# ============================================================
# Ansible Inventory - Hybrid Enterprise Network Security Lab
# Author: Vedakumara K H
# ============================================================

[cisco_asa]
ASA-FW-01 ansible_host=192.168.10.2 ansible_network_os=cisco.asa.asa ansible_user=admin ansible_password=cisco123 ansible_become=yes ansible_become_method=enable ansible_become_pass=cisco123

[cisco_iosxr]
CORE-RTR-01 ansible_host=192.168.1.1 ansible_network_os=cisco.iosxr.iosxr ansible_user=admin ansible_password=Admin@123

[fortigate]
FortiGate-01 ansible_host=192.168.30.1 ansible_network_os=fortinet.fortios.fortios ansible_user=admin ansible_password=Admin@123 ansible_httpapi_use_ssl=yes ansible_httpapi_validate_certs=no ansible_httpapi_port=443

[all:vars]
ansible_connection=network_cli
ansible_python_interpreter=/usr/bin/python3
